[workspace]
resolver = "2"

members = ["esocial", "qualicadastral", "utils", "xml"]

[workspace.dependencies]
utils = { path = "utils" }
xml = { path = "xml" }
chrono = "0.4.31"
log = "0.4"
structured-logger = "1.0.3"
