[workspace]
resolver = "2"

members = ["esocial", "qualicadastral", "utils", "xml"]

[workspace.dependencies]
utils = { path = "utils" }
xml = { path = "xml" }
chrono = "0.4.31"
log-panics = { version = "2", features = ["with-backtrace"] }
simplelog = "^0.12.0"

